name: laravel-build
run-name: ${{ github.actor }} is uploading new app version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - run: composer install --no-dev --no-interaction --prefer-dist    
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: tar -czf app.tgz ./*
      - name: Check DNS resolution and connectivity
        run: |
          echo "Checking DNS for ${{ secrets.SSH_HOST }}"
          nslookup ${{ secrets.SSH_HOST }}
          echo "Pinging ${{ secrets.SSH_HOST }}"
          ping -c 4 ${{ secrets.SSH_HOST }}
      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: '22'
          connect_timeout: 10s
          first_ssh: |
            cd ${{ secrets.SSH_DIR }}
            sudo mkdir -p ${{ secrets.SSH_DIR }}
            sudo chown -R www-data:www-data ${{ secrets.SSH_DIR }}
          scp: |
            './app.tgz' => ${{ secrets.SSH_DIR }}
          last_ssh: |
            cd ${{ secrets.SSH_DIR }} 
            tar -xzf app.tgz
            # Only copy if .env does not exist
            if [ ! -f .env ]; then
              cp env/env.example .env
            fi
